export const TEMPLATE_ACTIONS = {
  SET_SKU: 'SET_SKU',
  SET_NAME: 'SET_NAME',
  SET_DESCRIPTION: 'SET_DESCRIPTION',
  SET_CATEGORIES: 'SET_CATEGORIES',
  ADD_ATTRIBUTE: 'ADD_ATTRIBUTE',
  SET_ATTRIBUTE: 'SET_ATTRIBUTE',
  ADD_VARIATION: 'ADD_VARIATION',
  SET_VARIATION: 'SET_VARIATION',
  SET_VARIATION_ATTRIBUTE: 'SET_VARIATION_ATTRIBUTE',
}
